version: "3.8"

services:
  ssh-server:
    build: ./ssh-server
    ports:
      - "2222:22"
    networks:
      private_net:
        ipv4_address: 172.90.0.3  
        
  internal-web:
    build: ./internal-web
    expose:
      - "80"
    networks:
      private_net:
        ipv4_address: 172.90.0.2   

networks:
  private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/16
